name: 'Setup'
description: 'Setup environment with Java 21, Node 20'
runs:
  using: 'composite'
  steps:
    - name: 'Setup: Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: 'Setup: update NPM'
      shell: bash
      run: npm install -g npm
    - name: 'Setup: Java 21'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: 'Setup: check tools'
      shell: bash
      run: |
        node -v
        npm -v
        java -version
