spring:
  application:
    name: JhliteExtensionSample
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    tech:
      jhipster:
        lite:
          extension: INFO
jhlite:
  hidden-resources:
    # Disable the modules and its dependencies by slugs
    slugs: custom-jhlite
server:
  port: 8080
