name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  #--------------------------------------------------
  # Build and Tests the project on Linux
  #--------------------------------------------------
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v4
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Test: run tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      - name: 'Test: generate sample app'
        working-directory: ./tests-ci/
        run: |
          ./start.sh 7471
          ./generate.sh fullapp maven yaml
          ./stop.sh
      - name: 'Test: verify generated sample app'
        working-directory: /tmp/jhlite/fullapp/
        run: |
          if [ -f 'mvnw' ]; then
            ./mvnw clean verify
          elif [ -f 'gradlew' ]; then
            ./gradlew clean build --no-daemon --info
          else
            npm install
            npm test
          fi
